config/routes.rb
Rails.application.routes.draw do
  post "audio/save"
  resources :recordings
  resources :videoplaylists
  resources :videos
  resources :cinemas
  resources :musiques
  resources :newsarticles
  resources :songs do
    member do
      get "returntime"
    end
    collection do
      get "jouerunechanson"
      get "playmusique1"
      get "playmusique"
      get "musique"
    end
    
  end
  
  get "songs/returntime"
  resources :playlists
  resources :posts
  resources :emissions
  resources :animateurs
  get "/page/cookie", to: "posts#cookie", as: :pagecookie
  get "/page/conditions", to: "posts#conditions", as: :pageconditions
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :myanimateur
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :voirmonanimateur
  get "/list/animateur/p", to: "animateurs#index", as: :allanimateur
  get "/list/emission/p", to: "emissions#index", as: :allemission
  get "/post/emissions/:title-:id", to: "emissions#show", as: :myemission
  get "/list/actualite/p", to: "newsarticles#index", as: :listactualite
  get "/list/musique/p", to: "musiques#index", as: :listmusique
  get "/list/cinema/p", to: "cinemas#index", as: :listcinema
  get "/post/actualite/:title-:id", to: "newsarticles#show"
  get "/post/musique/:title-:id", to: "musiques#show"
  get "/post/cinema/:title-:id", to: "cinemas#show"
  get "grille", to: "emissions#grille"
  root to: 'welcome#index'
  get "post/hit/hit", to: "hit#post"
  get "post/hit/hit-:id", to: "hit#myhit"
  get "list/evenement/p", to: "hit#event"
  get "historique", to: "hit#historique"
  post "historique", to: "hit#getsongs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }

end

app/models/recording.rb
class Recording < ApplicationRecord
  after_validation :azertyuioiuy
  def azertyuioiuy
    if !self.duree
      self.duree=self.duration
    end
  end

  def duration
    t = Thread.new do
    @aa = `ffprobe -print_format json -show_streams -show_format -v error #{Rails.root.to_s+"/public/uploads/"+filename}`
        end
      t.join

    @aa
    JSON.parse(@aa)["format"]["duration"]
  rescue
    "my error"
  end

def recording=(uploaded_io)
myfilename=(0...8).map { (65 + rand(26)).chr }.join
File.open(Rails.root.join('public', 'uploads', myfilename+".wav"), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:filename,myfilename+".wav")

end
def filename
read_attribute(:filename)
end

end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: %i[ show edit update destroy ]

  # GET /recordings or /recordings.json
  def index
    @recordings = Recording.all
  end

  # GET /recordings/1 or /recordings/1.json
  def show
  end

  # GET /recordings/new
  def new
    @recording = Recording.new
  end

  # GET /recordings/1/edit
  def edit
  end

  # POST /recordings or /recordings.json
  def create
    @recording = Recording.new(recording_params)

    respond_to do |format|
      if @recording.save
        format.html { redirect_to recording_url(@recording), notice: "Recording was successfully created." }
        format.json { render :show, status: :created, location: @recording }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1 or /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        format.html { redirect_to recording_url(@recording), notice: "Recording was successfully updated." }
        format.json { render :show, status: :ok, location: @recording }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1 or /recordings/1.json
  def destroy
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url, notice: "Recording was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recording_params
      params.fetch(:recording, {})
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_with(model: recording) do |form| %>
  <% if recording.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
        <% recording.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recordings/_recording.html.erb
<div id="<%= dom_id recording %>">
</div>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render "form", recording: @recording %>

<br>

<div>
  <%= link_to "Show this recording", @recording %> |
  <%= link_to "Back to recordings", recordings_path %>
</div>

app/views/recordings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recordings</h1>

<div id="recordings">
  <% @recordings.each do |recording| %>
    <%= render recording %>
    <p>
      <%= link_to "Show this recording", recording %>
    </p>
  <% end %>
</div>

<%= link_to "New recording", new_recording_path %>

app/views/recordings/new.html.erb
<h1>New recording</h1>

<%= render "form", recording: @recording %>

<br>
<p id="notice"><%= notice %></p>
<div id="myplaylistid"><%=params[:playlist_id]%></div>
<div id="myemissionid"><%=params[:emission_id]%></div>

<p id="log"></p>
<%=content_for :title do%>
l'émission
<%end%>

<style>

</style>

      <header>

	<div id="controls">
		<img id="record" src="/img/mic128.png" onclick="toggleRecording(this);">
<form id="myvideoform"> </form>
<form id="myform"><textarea name="mycontent"></textarea> </form>
		<a id="save" href="#"><img src="/img/save.svg"></a>
	</div>


      </header>
   <div class="wrapper">


<div id="viz">
		<canvas id="analyser" width="1024" height="50"></canvas>
		<canvas id="wavedisplay" width="1024" height="50"></canvas>
	</div>


    </div>


<%=content_for :js do%>
<script src="/js/audiodisplay.js"></script>
        <script src="/js/recorderjs/recorder.js"></script>
        <script src="/js/main.js"></script>
<%end%>
<div>
  <%= link_to "Back to recordings", recordings_path %>
</div>

app/views/recordings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recording %>

<div>
  <%= link_to "Edit this recording", edit_recording_path(@recording) %> |
  <%= link_to "Back to recordings", recordings_path %>

  <%= button_to "Destroy this recording", @recording, method: :delete %>
</div>