config/routes.rb
Rails.application.routes.draw do
  post "audio/save"
  resources :recordings
  resources :videoplaylists
  resources :videos
  resources :cinemas
  resources :musiques
  resources :newsarticles
  resources :songs do
    member do
      get "returntime"
    end
    collection do
      get "jouerunechanson"
      get "playmusique1"
      get "playmusique"
      get "musique"
    end
    
  end
  
  get "songs/returntime"
  resources :playlists
  resources :posts
  resources :emissions
  resources :animateurs
  get "/page/cookie", to: "posts#cookie", as: :pagecookie
  get "/page/conditions", to: "posts#conditions", as: :pageconditions
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :myanimateur
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :voirmonanimateur
  get "/list/animateur/p", to: "animateurs#index", as: :allanimateur
  get "/list/emission/p", to: "emissions#index", as: :allemission
  get "/post/emissions/:title-:id", to: "emissions#show", as: :myemission
  get "/list/actualite/p", to: "newsarticles#index", as: :listactualite
  get "/list/musique/p", to: "musiques#index", as: :listmusique
  get "/list/cinema/p", to: "cinemas#index", as: :listcinema
  get "/post/actualite/:title-:id", to: "newsarticles#show"
  get "/post/musique/:title-:id", to: "musiques#show"
  get "/post/cinema/:title-:id", to: "cinemas#show"
  get "grille", to: "emissions#grille"
  root to: 'welcome#index'
  get "post/hit/hit", to: "hit#post"
  get "post/hit/hit-:id", to: "hit#myhit"
  get "list/evenement/p", to: "hit#event"
  get "historique", to: "hit#historique"
  post "historique", to: "hit#getsongs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }

end

app/models/animateur.rb
class Animateur < ApplicationRecord
    has_and_belongs_to_many :emissions, :join_table => :emissionhasanimateurs

  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
def self.leplusrecent
order(:created_at => :desc).limit(1)
end
def self.passebientot
order(:created_at => :desc).limit(1)
end
end

app/controllers/animateurs_controller.rb
class AnimateursController < ApplicationController
  before_action :set_animateur, only: %i[ show edit update destroy ]

  # GET /animateurs or /animateurs.json
  def index
    @animateurs = Animateur.all.page params[:page]
  end

  # GET /animateurs/1 or /animateurs/1.json
  def show
  end

  # GET /animateurs/new
  def new
    @animateur = Animateur.new
  end

  # GET /animateurs/1/edit
  def edit
  end

  # POST /animateurs or /animateurs.json
  def create
    @animateur = Animateur.new(animateur_params)

    respond_to do |format|
      if @animateur.save
        format.html { redirect_to animateur_url(@animateur), notice: "Animateur was successfully created." }
        format.json { render :show, status: :created, location: @animateur }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animateurs/1 or /animateurs/1.json
  def update
    respond_to do |format|
      if @animateur.update(animateur_params)
        format.html { redirect_to animateur_url(@animateur), notice: "Animateur was successfully updated." }
        format.json { render :show, status: :ok, location: @animateur }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animateurs/1 or /animateurs/1.json
  def destroy
    @animateur.destroy

    respond_to do |format|
      format.html { redirect_to animateurs_url, notice: "Animateur was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animateur
      @animateur = Animateur.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animateur_params
      params.require(:animateur).permit(:title,:subtitle, :image, :description,:job)
    end
end

app/helpers/animateurs_helper.rb
module AnimateursHelper
end

app/views/animateurs/_animateur.html.erb
      <li class="col-md-12 animateuritem" id="<%=dom_id animateur%>">
                                        <div class="wm-album-medium-wrap">
                                            <figure class="figure-listview">
                                                <a onmouseleave="mypic<%=animateur.id%>.classList.remove('hoverme')" onmouseenter="mypic<%=animateur.id%>.classList.add('hoverme')"  href="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>" class="ungraythumb">
                                                    <img width="290px" height="153px" src="/uploads/<%=animateur.image%>" alt="<%=animateur.title%>">
                                                    <span class="wm-hoverlink wm-color" id="mypic<%=animateur.id%>"><img src="/uploads/flaticonlink.png" /></span>
                                                </a>
                                            </figure>
                                            <div class="wm-album-medium-text">
                                                <h2 class="mytitle">
                                                    <a class="primary-color" href="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>"><%=animateur.title%></a>
                                                </h2>
                                                <h3 class="myjob">
                                                                                                            <span>
                                                                                                                        <a href="#"> <%=animateur.job%></a>
                                                                                                                    </span>
                                                                                                    </h3>
                                                <div class="social">
    <a data-sharer="facebook" data-hashtag="" data-url="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>"><i class="fa fa-2x fa-facebook-square"></i></a>
    <a data-sharer="twitter" data-hashtag="" data-url="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>"><i class="fa fa-2x fa-twitter-square"></i></a>
    <a data-sharer="linkedin" data-hashtag="" data-url="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>"><i class="fa fa-2x fa-linkedin-square"></i></a>
    <a data-sharer="pinterest" data-hashtag="" data-url="<%=voirmonanimateur_path(title: animateur.title.parameterize, id: animateur.id)%>"><i class="fa fa-2x fa-pinterest-square"></i></a>
</div>                                          
                                                <p class="mytext"><%=animateur.subtitle%></p>
                                            <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </li>

app/views/animateurs/_emissions.html.erb
<li class="col-md-4">
                                            <figure class="figure-animateurs_emissions"><a href="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><img src="/uploads/<%=emission.image%>" alt="<%=emission.title%>"></a>
                                                <figcaption>
                                                    <div class="wm-album-caption">
                                                        <div class="clearfix"></div>
                                                        <a href="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>" class="wm-album-linkbtn wm-color"><i class="flaticon-link"></i></a>
                                                    </div>
                                                </figcaption>
                                            </figure>
                                            <div class="wm-recent-releases-text">
                                                <time datetime="04:00">ma duree</time>
                                                <h2><a class="primary-color" href="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><%=emission.title%></a></h2>
                                            </div>
                                        </li>

app/views/animateurs/_form.html.erb
<%= form_with(model: animateur) do |form| %>
  <% if animateur.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animateur.errors.count, "error") %> prohibited this animateur from being saved:</h2>

      <ul>
        <% animateur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :job, style: "display: block" %>
    <%= form.text_field :job %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animateurs/edit.html.erb
<h1>Editing animateur</h1>

<%= render "form", animateur: @animateur %>

<br>

<div>
  <%= link_to "Show this animateur", @animateur %> |
  <%= link_to "Back to animateurs", animateurs_path %>
</div>

app/views/animateurs/index.html.erb
<p style="color: green"><%= notice %></p>
<%=content_for :title do%>
Notre équipe
<%end%>
<div class="wm-main-wrapper container" id="page-content-wrapper">

          <!--// Mini Header \\-->
<div class="wm-mini-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <ul class="mybreadcrumb">
        <li><a href="/">Accueil</a></li>
                    <li><a href="#">Liste animateurs</a></li>
            </ul>
                <div class="wm-page-heading">
                    <h1>Toutes les animateurs</h1>
                    <p>Découvrez les animateurs</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!--// Mini Header \\-->


    <div class="wm-main-content">
        <div class="wm-main-section wm-latestartist-albumfull">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <!--// Posts List \\-->
                        <div class="wm-album wm-album-medium">
                            <ul class="row">
                                    <%=render @animateurs%> 
                                <%if @animateurs.length == 0%>
                                <p>pas de posts
                                </p>
                                <%end%>
                                    
                                                            </ul>
                        </div>
                    </div>
                    <aside class="col-md-3">
                        <!-- on air -->
        
<%=render partial: "application/podcasts_aside", as: :animateur, collection: Animateur.passebientot%>    
    
                    
    
                        <!-- podcasts -->
<div class="widget wm_albumplayer_widget wm-albumplayer" style="display: none;">
    <div class="wm-widget-heading">
            <h2 style="color: #FFFFFF;">podcasts</h2>
        </div>
    <div id="jp_container_pocasts_aside" class="jp-audio" role="application" aria-label="media player">
        <div class="jp-type-playlist">
            <span class="jp-play"><i class="fa fa-pause"></i> <i class="fa fa-play"></i></span>
            <div id="jquery_jplayer_podcasts_aside" class="jp-jplayer"></div>
            <div class="jp-gui jp-interface">
                <div id="current-track_podcasts_aside" class="song-title">--</div>
                <div class="wm-player-wrap">
                    <span class="jp-previous"><i class="flaticon-arrows-1"></i></span>
                    <div class="jp-progress">
                        <div class="jp-seek-bar">
                            <div class="jp-play-bar"></div>
                        </div>
                    </div>
                    <span class="jp-next"><i class="flaticon-arrows-1"></i></span>
                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                </div>
            </div>
            <div class="jp-playlist">
                <ul>
                    <li>&nbsp;</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- /podcasts -->
    <!-- sociaux -->
                                                                <div class="wm-footer-social-media">
        <ul class="wm-footer-icons aside-footer-icons even-items">
                                                        </ul>
    </div>
    
    <!-- newsletter -->
                        </aside>
                </div>

                <div class="row mrgB">
    <div class="col-xs-12 pagination-container">
        <%if @animateurs.length > 0%>
          <%= paginate @animateurs %>
        <%end%>
    </div>
</div>
            </div>
        </div>
    </div>


    </div>

<%= link_to "New animateur", new_animateur_path %>

app/views/animateurs/new.html.erb
<h1>New animateur</h1>

<%= render "form", animateur: @animateur %>

<br>

<div>
  <%= link_to "Back to animateurs", animateurs_path %>
</div>

app/views/animateurs/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="wm-main-wrapper container" id="page-content-wrapper">


    

      
<!--// Mini Header \\-->
<div class="wm-mini-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <ul class="mybreadcrumb">
        <li><a href="/">Accueil</a></li>
                    <li><a href="/list/animateur/p">animateur</a></li>
                    <li><a href="#"><%=@animateur.title%></a></li>
            </ul>
                <div class="wm-page-heading">
                    <h1><%=@animateur.title%></h1>
                    <p></p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!--// Mini Header \\-->


    <!--// Main Content \\-->
    <div class="wm-main-content">

        <!--// Main Section \\-->
        <div class="wm-main-section wm-artistlist-full">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="wm-artist wm-artist-medium">
                            <ul class="row">
                                <li class="col-md-12">
                                                                            <figure class="figure-animateurs">
                                            <img src="/uploads/<%=@animateur.image%>" alt="<%=@animateur.title%>" class="img-responsive">
                                        </figure>
                                                                        <div class="wm-artist-text">
                                        <div class="wm-artist-title">
                                            <div class="wm-title">
                                                                                                                                                
                                                <span><%=@animateur.subtitle%></span>
                                            </div>
                                            <div class="social">
        <a target="_blank" href="https://soundcloud.com/royann_music/royann-dancehall-zone?ref=facebook&amp;p=i&amp;c=1 "><i class="fa fa-2x fa-soundcloud"></i></a>
        <a target="_blank" href="https://www.facebook.com/royann.zaga "><i class="fa fa-2x fa-facebook"></i></a>
        <a target="_blank" href="https://www.facebook.com/royann.zaga "><i class="fa fa-2x fa-instagram"></i></a>
    </div>                                        </div>
                                                                                <div>
                                          
                                                                                    <%=simple_format(@animateur.description)%>
                                                                            </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--// Main Section \\-->

                    <!--// Main Section \\-->
            <div class="wm-main-section wm-recent-releases-full">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="wm-simple-facny-title"><h2 class="primary-color">Ses emissions</h2></div>
                            <div class="wm-album wm-recent-releases-album">
                                <ul class="row d-flex-justify-center">
<%=render collection: @animateur.emissions, as: :emission, partial: "animateurs/emissions"%>
                                    
                                </ul>
                            </div>
                            <div class="wm-seeall-btn mrgB"><a href="/list/emission/p" class="wm-bgcolor">Toutes les emissions</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->
        
    </div>
    <!--// Main Content \\-->


</div>
<div>
  <%= link_to "Edit this animateur", edit_animateur_path(@animateur) %> |
  <%= link_to "Back to animateurs", animateurs_path %>

  <%= button_to "Destroy this animateur", @animateur, method: :delete %>
</div>