config/routes.rb
Rails.application.routes.draw do
  post "audio/save"
  resources :recordings
  resources :videoplaylists
  resources :videos
  resources :cinemas
  resources :musiques
  resources :newsarticles
  resources :songs do
    member do
      get "returntime"
    end
    collection do
      get "jouerunechanson"
      get "playmusique1"
      get "playmusique"
      get "musique"
    end
    
  end
  
  get "songs/returntime"
  resources :playlists
  resources :posts
  resources :emissions
  resources :animateurs
  get "/page/cookie", to: "posts#cookie", as: :pagecookie
  get "/page/conditions", to: "posts#conditions", as: :pageconditions
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :myanimateur
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :voirmonanimateur
  get "/list/animateur/p", to: "animateurs#index", as: :allanimateur
  get "/list/emission/p", to: "emissions#index", as: :allemission
  get "/post/emissions/:title-:id", to: "emissions#show", as: :myemission
  get "/list/actualite/p", to: "newsarticles#index", as: :listactualite
  get "/list/musique/p", to: "musiques#index", as: :listmusique
  get "/list/cinema/p", to: "cinemas#index", as: :listcinema
  get "/post/actualite/:title-:id", to: "newsarticles#show"
  get "/post/musique/:title-:id", to: "musiques#show"
  get "/post/cinema/:title-:id", to: "cinemas#show"
  get "grille", to: "emissions#grille"
  root to: 'welcome#index'
  get "post/hit/hit", to: "hit#post"
  get "post/hit/hit-:id", to: "hit#myhit"
  get "list/evenement/p", to: "hit#event"
  get "historique", to: "hit#historique"
  post "historique", to: "hit#getsongs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }

end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :playlists, :join_table => :playlistsongs
  
  after_validation :azertyuioiuy
  def azertyuioiuy
    if !self.duree
    self.duree=self.duration
    end
  end
  def image
    read_attribute(:image) || "no_album_art.png"
  end
  def duration
    t = Thread.new do
    @aa = `ffprobe -print_format json -show_streams -show_format -v error #{Rails.root.to_s+"/public/uploads/"+filename}`
        end
      t.join
    
    JSON.parse(@aa)["format"]["duration"]
  rescue
    "my error"
  end
  def self.findmysong(mydate)
    offset_utc=DateTime.now.formatted_offset(false).gsub("0","")
    x=offset_utc.to_i
    y=(-x)
    z=(y > 0 ? "+" : "")+y.to_s
   
    p z+" hours"
    mydate=DateTime.parse(mydate.to_s) - 2.hours
    
     @a=ActiveRecord::Base.connection.execute(send(:sanitize_sql_array, ["
      select playlistid,title,artist,heure_chanson, madureetotale,debut_chanson,moment_dans_chanson,now,
artist_suiv_2,title_suiv_2, suiv_filename_nb2,heure_chanson1,heure_chanson3,
artist_suiv_3, title_suiv_3, suiv_filename_nb3,image1st, image2, image3,heurechansonnow,heurechansonnow2,heurechansonnow3,
duree,filename, songid, playlistid,timenow,heure_derniere_chanson

    from (select playlists.*, strftime('%H:%M',datetime(ps.heure_chanson, '#{offset_utc} hours'))  as heurechansonnow,ps.heure_chanson, songs.duree,strftime('%H:%M:%S','now') as now,cast(strftime('%s','now') as float) - cast(strftime('%s',ps.heure_chanson) as float) as moment_dans_chanson,cast(strftime('%s',ps.heure_chanson) as float) as debut_chanson,cast(strftime('%s',ps.heure_chanson) as float) + songs.duree as madureetotale, playlists.id as playlistid,cast(strftime('%s','now') as float) as timenow, songs.*, songs.id as songid, row_number() OVER(partition by playlists.id order by ps.id) as row_num, max(heure_chanson) as heure_derniere_chanson,ifnull(songs.image, 'no_album_art.png') as image1st, (case when max(heure_chanson) = heure_chanson then duree else 0 end) as duree_derniere_chanson
 from playlists left join playlistsongs ps on ps.playlist_id = playlists.id left join songs on        songs.id = 
ps.song_id
group by songid,playlist_id

order by heure_chanson asc

) t1 
left outer join (
select 
 heure_chanson as heure_chanson1,strftime('%H:%M',datetime(ps1.heure_chanson, '#{offset_utc} hours'))  as heurechansonnow2,filename as suiv_filename_nb2, pl1.id as playlistid1, s1.title as title_suiv_2,s1.artist as artist_suiv_2, s1.id as songid1, row_number() OVER(partition by pl1.id order by ps1.id) as row_num1, max(heure_chanson) as heure_derniere_chanson1, (case when max(heure_chanson) = heure_chanson then duree else 0 end) as duree_derniere_chanson1, ifnull(s1.image, 'no_album_art.png') as image2
 from playlists pl1 left join playlistsongs ps1 on ps1.playlist_id = pl1.id left join songs s1
on s1.id = ps1.song_id
group by songid1,playlistid1

order by heure_chanson asc
)t2_suiv on t2_suiv.heure_chanson1 > t1.heure_chanson
left outer join (
select 
 ps3.heure_chanson as heure_chanson3,ifnull(s3.image, 'no_album_art.png') as image3,filename as suiv_filename_nb3, pl3.id as playlistid3, s3.title as title_suiv_3,s3.artist as artist_suiv_3,strftime('%H:%M',datetime(ps3.heure_chanson,'#{offset_utc} hours'))  as heurechansonnow3,  s3.id as songid3, row_number() OVER(partition by pl3.id order by ps3.id) as row_num3, max(heure_chanson) as heure_derniere_chanson3, (case when max(heure_chanson) = heure_chanson then duree else 0 end) as duree_derniere_chanson3
 from playlists pl3 left join playlistsongs ps3 on ps3.playlist_id = pl3.id left join songs s3
on s3.id = ps3.song_id
group by songid3,playlistid3

order by heure_chanson asc
)t3_suiv on t3_suiv.heure_chanson3 > t2_suiv.heure_chanson1

group by songid, playlistid
having (cast(strftime('%s',heure_chanson) as float)+duree > cast(strftime('%s', ?) as float))
and (cast(strftime('%s',heure_chanson) as float) < cast(strftime('%s', ?) as float))
order by cast(strftime('%s', DATETIME(heure_chanson, '#{z} hours')) as float) asc

 
      ", mydate,mydate]))
p @a[0]
  if @a[0]
    @a.take(3)
  else
    []
  end
  end
  def filename=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:filename, uploaded_io.original_filename)
  end
  def filename
    read_attribute(:filename)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy returntime ]
  protect_from_forgery except: [:update]
  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  def returntime
        respond_to do |format|

    format.js {render js: :returntime}
        end
  end
  def jouerunechanson
    @a=Playlist.myotherplaylist||{}
    respond_to do |format|
        format.json { render json: @a, status: :ok }
    end
  end
  # DELETE /songs/1 or /songs/1.json
  def musique
    respond_to do |format|
        format.json { render json: {ok: session[:playmusique], myvol: session[:myvol]}, status: :ok }
    end
  end
  def playmusique1
     session[:myvol] = params[:myvol].to_s
    respond_to do |format|
        format.json { render json: session[:playmusique], status: :ok }
    end
  end
  def playmusique
    session[:playmusique] = params[:play].to_s
    session[:myvol] = params[:myvol].to_s
    respond_to do |format|
        format.json { render json: session[:playmusique], status: :ok }
    end
  end
  
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :filename,:duree)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>
  <div>
    <%= form.label :filename, style: "display: block" %>
    <%= form.file_field :filename %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p>
    <strong>Title:</strong>
    <%= song.title %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= song.artist %>
  </p>

  <p>
    <strong>Duree en seconde:</strong>
    <span class="duree"><%= song.duree || "O" %>s</span>
  </p>
  <p>
      <!--<audio src="/uploads/<%=song.filename%>" controls></audio>-->
  </p>
</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Songs</h1>

<div id="songs">
  <% @songs.each do |song| %>
    <%= render song %>
    <p>
      <%= link_to "Show this song", song %>
    </p>
  <% end %>
</div>

<%= link_to "New song", new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>
<%=content_for :asomejs do%>
<script>
window.onload=function(){
function a(){
/*$.ajax({url: '<%=returntime_song_path(@song.id)%>', success:function(data){}});*/
	var audio1 = new Audio('/uploads/'+("<%=@song.filename.html_safe%>"));
	audio1.addEventListener("loadedmetadata", setSliderMax);
        
	function setSliderMax() {
                $.ajax({url: "/songs/<%=@song.id%>.json", data: {song: {duree: audio1.duration}}, type: "patch",
                success:function(data){
                  $(".duree").html(String(data.duree)+"s")
                }
                });
               
                
	}
return false;
};
a();
};
</script>
<%end%>