config/routes.rb
Rails.application.routes.draw do
  post "audio/save"
  resources :recordings
  resources :videoplaylists
  resources :videos
  resources :cinemas
  resources :musiques
  resources :newsarticles
  resources :songs do
    member do
      get "returntime"
    end
    collection do
      get "jouerunechanson"
      get "playmusique1"
      get "playmusique"
      get "musique"
    end
    
  end
  
  get "songs/returntime"
  resources :playlists
  resources :posts
  resources :emissions
  resources :animateurs
  get "/page/cookie", to: "posts#cookie", as: :pagecookie
  get "/page/conditions", to: "posts#conditions", as: :pageconditions
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :myanimateur
  get "/post/animateur/:title-:id", to: "animateurs#show", as: :voirmonanimateur
  get "/list/animateur/p", to: "animateurs#index", as: :allanimateur
  get "/list/emission/p", to: "emissions#index", as: :allemission
  get "/post/emissions/:title-:id", to: "emissions#show", as: :myemission
  get "/list/actualite/p", to: "newsarticles#index", as: :listactualite
  get "/list/musique/p", to: "musiques#index", as: :listmusique
  get "/list/cinema/p", to: "cinemas#index", as: :listcinema
  get "/post/actualite/:title-:id", to: "newsarticles#show"
  get "/post/musique/:title-:id", to: "musiques#show"
  get "/post/cinema/:title-:id", to: "cinemas#show"
  get "grille", to: "emissions#grille"
  root to: 'welcome#index'
  get "post/hit/hit", to: "hit#post"
  get "post/hit/hit-:id", to: "hit#myhit"
  get "list/evenement/p", to: "hit#event"
  get "historique", to: "hit#historique"
  post "historique", to: "hit#getsongs"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }

end

app/models/emission.rb
class Emission < ApplicationRecord
  has_and_belongs_to_many :animateurs, :join_table => :emissionhasanimateurs
  has_and_belongs_to_many :weekdays, :join_table => :hasweekdays
    def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/controllers/emissions_controller.rb
class EmissionsController < ApplicationController
  before_action :set_emission, only: %i[ show edit update destroy ]

  # GET /emissions or /emissions.json
  def index
    @emissions = Emission.all.page params[:page]
    @weekdays = Weekday.all
  end
  def grille
    @emissions = Emission.all
    @weekdays = Weekday.all
  end

  # GET /emissions/1 or /emissions/1.json
  def show
  end

  # GET /emissions/new
  def new
    @emission = Emission.new
  end

  # GET /emissions/1/edit
  def edit
  end

  # POST /emissions or /emissions.json
  def create
    @emission = Emission.new(emission_params)

    respond_to do |format|
      if @emission.save
        format.html { redirect_to emission_url(@emission), notice: "Emission was successfully created." }
        format.json { render :show, status: :created, location: @emission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emissions/1 or /emissions/1.json
  def update
    respond_to do |format|
      if @emission.update(emission_params)
        format.html { redirect_to emission_url(@emission), notice: "Emission was successfully updated." }
        format.json { render :show, status: :ok, location: @emission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emissions/1 or /emissions/1.json
  def destroy
    @emission.destroy

    respond_to do |format|
      format.html { redirect_to emissions_url, notice: "Emission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emission
      @emission = Emission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emission_params
      params.require(:emission).permit(:title,:subtitle, :image, :description,:duree_emission,:heure_emission, :animateur_ids=>[],:weekday_ids=>[])
    end
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/views/emissions/_emission.html.erb
<li class="col-md-12">
                                        <div class="wm-album-medium-wrap">
                                            <figure class="figure-listview">
                                                <a href="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>" class="ungraythumb">
                                                    <img src="/uploads/<%=emission.image%>" alt="<%=emission.title%>">
                                                    <span class="wm-hoverlink wm-color"><i class="flaticon-link"></i></span>
                                                </a>
                                            </figure>
                                            <div class="wm-album-medium-text">
                                                <h2 class="mytitle">
                                                    <a class="primary-color" href="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><%=emission.title%></a>
                                                </h2>
                                                <ul class="wm-album-options">
                                                                                                    </ul>
                                                <div class="social">
    <a data-sharer="facebook" data-hashtag="" data-url="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><i class="fa fa-2x fa-facebook-square"></i></a>
    <a data-sharer="twitter" data-hashtag="" data-url="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><i class="fa fa-2x fa-twitter-square"></i></a>
    <a data-sharer="linkedin" data-hashtag="" data-url="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><i class="fa fa-2x fa-linkedin-square"></i></a>
    <a data-sharer="pinterest" data-hashtag="" data-url="<%=myemission_path(title: emission.title.parameterize, id: emission.id)%>"><i class="fa fa-2x fa-pinterest-square"></i></a>
</div>                                                <p  class="mytext"><%=emission.subtitle%>!</p>
                                            <div class="clearfix"></div>
                                            </div>
                                        </div>
                                    </li>

app/views/emissions/_form.html.erb
<%= form_with(model: emission) do |form| %>
  <% if emission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(emission.errors.count, "error") %> prohibited this emission from being saved:</h2>

      <ul>
        <% emission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_area :subtitle %>
  </div>
  <div>

  </div>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :duree_emission, style: "display: block" %>
    <%= form.time_field :duree_emission,
      value: (emission.duree_emission ? l(emission.duree_emission, format: :mytime) : "%H:%M"),
      min: 'hh:mm:ss',
      max: 'hh:mm:ss' %>
  </div>
  <div>
    <%= form.label :heure_emission, style: "display: block" %>
    <%= form.time_field :heure_emission,
      value: (emission.heure_emission ? l(emission.heure_emission, format: :mytime) : "%H:%M"),
      min: 'hh:mm:ss',
      max: 'hh:mm:ss' %>
  </div>

<div>
    animateur/trice
     <%= form.select(:animateur_ids, Animateur.all.collect {|p| [ p.title, p.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true, :size => 5 }) %>

    </div>
<div>
    jours de la semaine
     <%= form.select(:weekday_ids, Weekday.all.collect {|p| [ p.name, p.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true, :size => 7 }) %>

    </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/emissions/_myradio.html.erb
<div class="wm-artist-slider-layer">
                                    <figure class="figure-234x170">
                                        <a href="<%=myanimateur_path(id: animateur.id, title: animateur.title.parameterize)%>">
                                            <img src="/uploads/<%=animateur.image%>" alt="ROYANN">
                                        </a>
                                        <figcaption>
                                            <a href="/post/animateur/royann-1559851503">
                                                <i class="flaticon-link"></i>
                                            </a>
                                        </figcaption>
                                    </figure>
                                    <div class="wm-artist-title">
                                        <h2 class="primary-color"><a class="primary-color" href="<%=myanimateur_path(id: animateur.id, title: animateur.title.parameterize)%>"><%=animateur.title%></a></h2>
                                        <p>
                                                                                    <span>
                                                                                                 <%=animateur.job%>
                                                                                            </span>
                                                                                </p>
                                    </div>
                                </div>

app/views/emissions/edit.html.erb
<h1>Editing emission</h1>

<%= render "form", emission: @emission %>

<br>

<div>
  <%= link_to "Show this emission", @emission %> |
  <%= link_to "Back to emissions", emissions_path %>
</div>

app/views/emissions/grille.html.erb
<p style="color: green"><%= notice %></p>

<div class="wm-main-wrapper container" id="page-content-wrapper">


    

      
<!--// Mini Header \\-->
<div class="wm-mini-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <ul class="mybreadcrumb">
        <li><a href="/">Accueil</a></li>
                    <li><a href="#">Grille des programmes NRJ</a></li>
            </ul>
                <div class="wm-page-heading">
                    <h1>Grille des programmes NRJ</h1>
                    <p>du 01/05/2019 au 24/05/2024</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!--// Mini Header \\-->


<div class="wm-main-content">
    <div class="wm-main-section wm-eventcalendar-full">
        <div class="container">
            <%if @emissions.length > 0%>
            <div class="col-md-9 col-xs-12">
                <div id="planning-viewer"  class=" row planning">
<div class="nav nav-tabs row day-names"><table><thead class="fc-head">
            
            <tr><td class="fc-head-container fc-widget-header"><div class="fc-row fc-widget-header"><table>
<thead>
    <tr>
        <%@weekdays.each_with_index do |x,i|%>
        <th class="fc-day-header fc-widget-header fc-sun <%=i == 0 ? "active" : ""%>">
<a class="nav-link <%=i == 0 ? "active" : ""%>" id="<%=x.name.downcase%>-tab" data-bs-toggle="tab" data-bs-target="#<%=x.name.downcase%>" type="button" role="tab" aria-controls="<%=x.name.downcase%>" aria-selected="<%=i == 0 ? "true" : "false"%>" href="javascript:void(0);" >
<span><%=x.name%></span></a></th> 
    <%end%>
    </tr></thead></table></div></td></tr></thead></table></div> 
                    <div class="tab-content" id="myTabContent">
                    <%@weekdays.each_with_index do |w,i|%>
                        <div class="tab-pane fade <%=i == 0 ? " show active" : ""%>" id="<%=w.name.downcase%>" role="tabpanel" aria-labelledby="<%=w.name.downcase%>-tab">
<div class="col-md-12 col-xs-12">
    <%w.emissions.each do |e|%>
    <div class="row emissions my-1">
        <div class="col-md-2 emission-duree hidden-xs"><time class="timeline-time"><%=l(e.duree_emission, format: :mytime)%></time></div> <div class="col-md-10 emission-info col-xs-12"><h2 class="timeline-time visible-xs"><%=l(e.heure_emission, format: :mytime)%></h2> <div class="emission-img"><a href="/post/emission/la-playlist-nrj-1558701359"><img src="/uploads/<%=e.image%>" class="img-responsive"></a></div> <div class="emission-txt"><h2><%=e.title%></h2> <p><%=e.subtitle%></p> <div class="emission-link"><a href="<%=myemission_path(title: e.title.parameterize, id: e.id)%>"><i aria-hidden="true" class="fa fa-chevron-circle-right"></i></a></div></div></div>
    </div> 
        <%end%>
        

</div>
                        </div>
                    <%end%><!----> <!----> <!----> <!----> <!----> <!---->
                    </div>
                    </div>
            </div>
            <%else%>
            <p>pas d'emissions pour le moment</p>
<%end%>
            <aside class="col-md-3 col-xs-12">
                    <!-- on air -->
        
    <div id="aside_onair" class="widget widget_on_air"><div class="emission-onair" style="background-image: url(&quot;https://nrjguyane.fm/media/cache/on_air_nav/uploads/media/nrjguyanefm/1180x400-royann-2.jpg&quot;);"><a href="/post/emission/c-royann-de-15h-a-19h-sur-nrj-1663361364"><div class="emission-title"><h4>en direct</h4> <h5>C'ROYANN DE 15H A 19H SUR NRJ</h5></div></a></div></div>
    
    
                    
    
    
    <!-- sociaux -->
                                                                <div class="wm-footer-social-media">
        <ul class="wm-footer-icons aside-footer-icons even-items">
                                                        </ul>
    </div>
    
    <!-- newsletter -->
                </aside>
        </div>
    </div>
</div>




</div>

<%= link_to "New emission", new_emission_path %>

app/views/emissions/index.html.erb
<p style="color: green"><%= notice %></p>
<%=content_for :title do%>
Notre équipe
<%end%>
<div class="wm-main-wrapper container" id="page-content-wrapper">

          <!--// Mini Header \\-->
<div class="wm-mini-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <ul class="mybreadcrumb">
        <li><a href="/">Accueil</a></li>
                    <li><a href="#">Liste emissions</a></li>
            </ul>
                <div class="wm-page-heading">
                    <h1>Toutes les emissions</h1>
                    <p>Découvrez les emissions</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!--// Mini Header \\-->


    <div class="wm-main-content">
        <div class="wm-main-section wm-latestartist-albumfull">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <!--// Posts List \\-->
                        <div class="wm-album wm-album-medium">
                            <ul class="row">
                                    <%=render @emissions%> 
                                <%if @emissions.length == 0%>
                                <p>pas de posts
                                </p>
                                <%end%>
                                    
                                                            </ul>
                        </div>
                    </div>
                    <aside class="col-md-3">
                        <!-- on air -->
        
<%=render partial: "application/podcasts_aside", as: :animateur, collection: Animateur.passebientot%>    
    
                    
    
                        <!-- podcasts -->
<div class="widget wm_albumplayer_widget wm-albumplayer" style="display: none;">
    <div class="wm-widget-heading">
            <h2 style="color: #FFFFFF;">podcasts</h2>
        </div>
    <div id="jp_container_pocasts_aside" class="jp-audio" role="application" aria-label="media player">
        <div class="jp-type-playlist">
            <span class="jp-play"><i class="fa fa-pause"></i> <i class="fa fa-play"></i></span>
            <div id="jquery_jplayer_podcasts_aside" class="jp-jplayer"></div>
            <div class="jp-gui jp-interface">
                <div id="current-track_podcasts_aside" class="song-title">--</div>
                <div class="wm-player-wrap">
                    <span class="jp-previous"><i class="flaticon-arrows-1"></i></span>
                    <div class="jp-progress">
                        <div class="jp-seek-bar">
                            <div class="jp-play-bar"></div>
                        </div>
                    </div>
                    <span class="jp-next"><i class="flaticon-arrows-1"></i></span>
                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                </div>
            </div>
            <div class="jp-playlist">
                <ul>
                    <li>&nbsp;</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- /podcasts -->
    <!-- sociaux -->
                                                                <div class="wm-footer-social-media">
        <ul class="wm-footer-icons aside-footer-icons even-items">
                                                        </ul>
    </div>
    
    <!-- newsletter -->
                        </aside>
                </div>

                <div class="row mrgB">
    <div class="col-xs-12 pagination-container">
        <%if @emissions.length > 0%>
          <%= paginate @emissions %>
        <%end%>
    </div>
</div>
            </div>
        </div>
    </div>


    </div>

<%= link_to "New emission", new_emission_path %>

app/views/emissions/new.html.erb
<h1>New emission</h1>

<%= render "form", emission: @emission %>

<br>

<div>
  <%= link_to "Back to emissions", emissions_path %>
</div>

app/views/emissions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="wm-main-wrapper container" id="page-content-wrapper">

      
<!--// Mini Header \\-->
<div class="wm-mini-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <ul class="mybreadcrumb">
        <li><a href="/">Accueil</a></li>
                    <li><a href="/list/emission/p">emission</a></li>
                    <li><a href="#"><%=@emission.title%></a></li>
            </ul>
                <div class="wm-page-heading">
                    <h1><%=@emission.title%></h1>
                    <p></p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<!--// Mini Header \\-->



<!--// Main Content \\-->
<div class="wm-main-content">

    <!--// Main Section \\-->
    <div class="wm-main-section wm-albumsingle-full">
        <div class="container">
            <div class="row">
                <aside class="col-md-4">
                    <div class="mrgB text-center">
                        <figure>
                                                        <div id="ad_300_600">
                                <!-- NRJ GUYANE - 300x600 -->
                            </div>
                                                    </figure>
                    </div>
                </aside>

                <div class="col-md-8">

                    <!--// Emissions \\-->
                    <div class="wm-album wm-album-medium">
                        <ul class="row">
                            <li class="col-md-12">
                                <div class="wm-album-medium-wrap">
                                                                                                            <figure class="figure-emissions h-auto">
                                        <a href="#" class="ungraythumb">
                                            <img src="/uploads/<%=@emission.image%>" alt="<%=@emission.title%>">
                                        </a>
                                    </figure>
                                                                        <div class="wm-album-medium-text">
                                                                                <div class="social">
    <a data-sharer="facebook" data-hashtag="" data-url="https://www.nrjguyane.fm/post/emission/c-royann-de-15h-a-19h-sur-nrj-1663361364"><i class="fa fa-2x fa-facebook-square"></i></a>
    <a data-sharer="twitter" data-hashtag="" data-url="https://www.nrjguyane.fm/post/emission/c-royann-de-15h-a-19h-sur-nrj-1663361364"><i class="fa fa-2x fa-twitter-square"></i></a>
    <a data-sharer="linkedin" data-hashtag="" data-url="https://www.nrjguyane.fm/post/emission/c-royann-de-15h-a-19h-sur-nrj-1663361364"><i class="fa fa-2x fa-linkedin-square"></i></a>
    <a data-sharer="pinterest" data-hashtag="" data-url="https://www.nrjguyane.fm/post/emission/c-royann-de-15h-a-19h-sur-nrj-1663361364"><i class="fa fa-2x fa-pinterest-square"></i></a>
</div>                                        <ul class="wm-album-options">
                                            <li><span class="wm-bgcolor wm-album-track-count">Durée&nbsp;04:00</span></li>
                                                                                          <li><span>lundi</span> : 15:00 - 19:00</li>
                                                                                          <li><span>mardi</span> : 15:00 - 19:00</li>
                                                                                          <li><span>mercredi</span> : 15:00 - 19:00</li>
                                                                                          <li><span>jeudi</span> : 15:00 - 19:00</li>
                                                                                          <li><span>vendredi</span> : 15:00 - 19:00</li>
                                                                                    </ul>
                                        <%=@emission.subtitle%>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!--// Emissions \\-->

                    <!--// Description, contenu \\-->
                    <div class="wm-editore">
                        <div class="wm-blog-heading">
                            <h2 class="primary-color">description</h2>
                        </div>
                        <p><%=@emission.description%></p>
                    </div>
                    <!--// Description, contenu \\-->

                    
                                                            <div class="wm-albumteam-wrap">
                                                                <%if @emission.animateurs.length > 0%>
                        <div class="wm-blog-heading">
                            <h2>animateurs</h2>
                        </div>
                        <div class="wm-artist-grid wm-albumteam-slider">

                                                                                        <%=render collection: @emission.animateurs, as: :animateur, partial: "emissions/myradio"%>
                            
                        </div>
                                                                
                                                                <%end%>
                    </div>
                                                        </div>
            </div>
        </div>
    </div>
    <!--// Main Section \\-->

</div>
<!--// Main Content \\-->


    </div>

<div>
  <%= link_to "Edit this emission", edit_emission_path(@emission) %> |
  <%= link_to "Back to emissions", emissions_path %>
  <%= link_to "parler dans l'émission (nouvelle playlist)", new_playlist_path(myemission_id:@emission.id) %>

  <%= button_to "Destroy this emission", @emission, method: :delete %>
</div>